emsi/urls.py
from django.urls import path
from . import views
app_name = 'emsi'
urlpatterns = [

# Authentication
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

# Employee
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/<str:sort>', views.emp_sort, name='emp_sort'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),
    path('dashboard/employee/<int:pk>/delete/', views.emp_delete, name='employee_delete'),

#Department
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Salary
    path("employee/pay/",views.Pay.as_view(), name="Salary")

]

emsiPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import emsi

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emsi.urls', namespace = 'emsi')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emsi/models.py
from django.db import models
import random
from django.urls import reverse
from django.utils import timezone
import time
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    thumb = models.ImageField()


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=70, null=False, blank=False)
    history = models.TextField(max_length=1000, null=True, blank=True, default='No History')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("emsi:dept_detail", kwargs={"pk": self.pk})


class Employee(models.Model):
    LANGUAGE = (('english', 'ENGLISH'), ('arabic', 'ARABIC'), ('french', 'FRENCH'))
    GENDER = (('male', 'MALE'), ('female', 'FEMALE'))
    emp_id = models.CharField(max_length=70, default='emp' + str(random.randrange(100, 999, 1)))
    thumb = models.ImageField(blank=True, null=True)
    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=50, null=False)
    mobile = models.CharField(max_length=15)
    email = models.EmailField(max_length=125, null=False)
    address = models.TextField(max_length=100, default='')
    emergency = models.CharField(max_length=11)
    gender = models.CharField(choices=GENDER, max_length=10)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    joined = models.DateTimeField(default=timezone.now)
    language = models.CharField(choices=LANGUAGE, max_length=10, default='english')
    nuban = models.CharField(max_length=10, default='0123456789')
    bank = models.CharField(max_length=25, default='First Bank Plc')
    salary = models.CharField(max_length=16, default='00,000.00')

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse("emsi:employee_view", kwargs={"pk": self.pk})

emsi/forms.py
from django.contrib.auth import get_user_model
from .models import Employee,Department
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms
from django.core import validators
from django.utils import timezone
from django.db.models import Q
import time
class RegistrationForm (UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Valid Email is required'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password'}))
    thumb = forms.ImageField(label='Attach a Passport Photograph',required=True,widget=forms.FileInput(attrs={'class':'form-control mt-2'}))
    class Meta:
        model = get_user_model()
        fields = ('username','email','password1', 'password2','thumb')

class LoginForm(AuthenticationForm):
   username = forms.CharField(widget=forms.TextInput(attrs={'autofocus':True, 'placeholder':'Username Here', 'class':'form-control'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'********'}))

class EmployeeForm (forms.ModelForm):
    thumb = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(strip=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}))
    last_name = forms.CharField(strip=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}))
    mobile = forms.CharField(strip=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Mobile Number'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Valid Email'}))
    emergency = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Relative Mobile Number'}))
    gender = forms.ChoiceField(choices=Employee.GENDER,widget=forms.Select(attrs={'class':'form-control'}))
    department = forms.ModelChoiceField(Department.objects.all(),required=True, empty_label='Select a department',widget=forms.Select(attrs={'class':'form-control'}))
    language = forms.ChoiceField(choices=Employee.LANGUAGE,widget=forms.Select(attrs={'class':'form-control'}))

    class Meta:
        model = Employee
        fields = ('first_name', 'last_name', 'mobile','email','emergency','salary','gender','department','bank','nuban','language','thumb')
        widgets={
            'salary':forms.TextInput(attrs={'class':'form-control'}),
            'bank':forms.TextInput(attrs={'class':'form-control'}),
            'nuban':forms.TextInput(attrs={'class':'form-control'})
        }



class DepartmentForm(forms.ModelForm):
    name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Department Name'}))
    history = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Brief Department History'}))
    
    class Meta:
        model = Department
        fields = '__all__'

emsi/views.py
from django.shortcuts import render, redirect, resolve_url, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from pip._vendor.requests import Response

from .models import Employee, Department
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, CreateView, View, DetailView, TemplateView, ListView, UpdateView, DeleteView
from .forms import RegistrationForm, LoginForm, EmployeeForm, DepartmentForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q


# Create your views here.
class Index(TemplateView):
    template_name = 'emsi/home/home.html'


#   Authentication
class Register(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'emsi/registrations/register.html'
    success_url = reverse_lazy('emsi:login')


class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'emsi/registrations/login.html'

    def get_success_url(self):
        url = resolve_url('emsi:dashboard')
        return url


class Logout_View(View):

    def get(self, request):
        logout(self.request)
        return redirect('emsi:login', permanent=True)


# Main Board
class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'emsi/dashboard/index.html'
    login_url = 'emsi:login'
    model = get_user_model()
    context_object_name = 'qset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.all().count()
        context['workers'] = Employee.objects.order_by('-id')
        return context


# Employee's Controller
class Employee_New(LoginRequiredMixin, CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'emsi/employee/create.html'
    login_url = 'emsi:login'
    redirect_field_name = 'redirect:'


class Employee_All(LoginRequiredMixin, ListView):
    template_name = 'emsi/employee/index.html'
    model = Employee
    login_url = 'emsi:login'
    context_object_name = 'employees'
    paginate_by = 5


class Employee_View(LoginRequiredMixin, DetailView):
    queryset = Employee.objects.select_related('department')
    template_name = 'emsi/employee/single.html'
    context_object_name = 'employee'
    login_url = 'emsi:login'


class Employee_Update(LoginRequiredMixin, UpdateView):
    model = Employee
    template_name = 'emsi/employee/edit.html'
    form_class = EmployeeForm
    login_url = 'emsi:login'


class Employee_Delete(DeleteView):
    model = Employee
    template_name = 'emsi/employee/index.html'
    success_url = reverse_lazy('dashboard:employee')


def emp_delete(request,pk):
    emp_ins = Employee.objects.get(id = int(pk))
    emp_ins.delete()
    return redirect('/dashboard/employee/')


def emp_sort(request,sort):
    emp_all = Employee.objects.all().order_by(sort)
    context = {
        'employees':emp_all
    }
    return render(request,'emsi/employee/index.html',context)





# Department views

class Department_Detail(LoginRequiredMixin, ListView):
    context_object_name = 'employees'
    template_name = 'emsi/department/single.html'
    login_url = 'emsi:login'

    def get_queryset(self):
        queryset = Employee.objects.filter(department=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dept"] = Department.objects.get(pk=self.kwargs['pk'])
        return context


class Department_New(LoginRequiredMixin, CreateView):
    model = Department
    template_name = 'emsi/department/create.html'
    form_class = DepartmentForm
    login_url = 'emsi:login'


class Department_Update(LoginRequiredMixin, UpdateView):
    model = Department
    template_name = 'emsi/department/edit.html'
    form_class = DepartmentForm
    login_url = 'emsi:login'
    success_url = reverse_lazy('emsi:dashboard')


class Salary(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'emsi/Salary/index.html'
    login_url = 'emsi:login'
    context_object_name = 'stfpay'


class Pay(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'emsi/Salary/index.html'
    context_object_name = 'emps'
    login_url = 'emsi:login'

emsi/templates/emsi/footer.html
<footer class="footer bg-dark text-white">
          <div class="container-fluid clearfix">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2021
              <a  target="_blank">ElHalloumi @</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Developed By ElHalloumi Abdelkarim
              </i>
            </span>
          </div>
</footer>

emsi/templates/emsi/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'emsi/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'emsi/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">
 
  
  <link rel="stylesheet" href="{% static 'emsi/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'emsi/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'emsi/images/favicon.png' %}" />
</head>
  
<body>
  <div class="container-scroller">
    {% include "emsi/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'emsi/sidebar.html' %}
        {% block content %} {% endblock content %}
        {% include 'emsi/footer.html' %}
    </div>
  </div>
  <!-- plugins:js -->
  
  <script src="{% static 'emsi/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'emsi/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'emsi/js/toastr.min.js' %}"></script>
  <script src="{% static 'emsi/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'emsi/js/pay.js' %}"></script>


  {% block noty %}
  {% endblock noty %}
</body>

</html>

emsi/templates/emsi/nav.html
    {% load static %}
    <nav class="navbar default-layout bg-success col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center bg-dark">
        <p class="display-4 mt-3 text-light">EMSI-PROJECT</p>
        <a class="navbar-brand brand-logo-mini" href="{% url 'emsi:dashboard' %}">
        
          <img src="{{user.thumb.url}}" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center bg-dark">
        
        <ul class="navbar-nav navbar-nav-right">          
          <li class="nav-item dropdown d-none d-xl-inline-block">
          
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text"> Hello, {{user.username | upper }} ! </span>
              <img class="img-xs rounded-circle" src=" {{user.thumb.url}} " alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              {% comment %} <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a> {% endcomment %}
              {% comment %} <a class="dropdown-item mt-2">
                Manage Accounts
              </a>
              <a class="dropdown-item">
                Change Password
              </a>
              <a class="dropdown-item">
                Check Inbox
              </a> {% endcomment %}
              <a class="dropdown-item" href='{% url 'emsi:logout' %}'>
                Log Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

emsi/templates/emsi/sidebar.html
<nav class="sidebar sidebar-offcanvas bg" id="sidebar" >
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{user.thumb.url}}">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user.username | upper}} </p>
                  <div>
                    <small class="designation text-muted">Administrator</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
                </div>

                </div>

          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'emsi:dashboard' %}">
              <i class="fa  fa-dashboard"></i>
              <span class="menu-title">&emsp;Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'emsi:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-user text-dark"></i>
              <span class="menu-title">&emsp;Employees</span>
            </a>
          </li>



          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-folder "></i>
              <span class="menu-title">&emsp;Department</span>
              <i class="menu-arrow"></i>
            </a>
              <a class="nav-link" href="{% url 'emsi:dept_new' %}"><i class="fa fa-plus"></i>&emsp;New Department</a>
              
            <hr>

            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
              {% for dept in depts  %}
                <li class="nav-item">
                  <a class="nav-link" href="{{dept.get_absolute_url}}">{{dept.name}}</a>
                </li>
              {% endfor %}
              </ul>
            </div>
          </li>




          <li class="nav-item">
            <a class="nav-link" href="{% url 'emsi:Salary' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Salary</span>
            </a>
          </li>

          {% comment %} <li class="nav-item">

          <li class="nav-item">
            <a class="nav-link" href="pages/icons/font-awesome.html">
              <i class="fa  fa-gears"></i>
              <span class="menu-title">&emsp;Settings</span>
            </a>
          </li> {% endcomment %}
        </ul>
      </nav>